config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :posts do
    resources :comments
  end
  root 'posts#index'
  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base  
  belongs_to :user
  belongs_to :post
end

app/models/place.rb
class Place < ApplicationRecord
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates_length_of :about, :allow_blank => false
  validates :user_id, presence: true
  validates :image, presence: true
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  has_many :comments, dependent: :destroy
  geocoded_by :address   # can also be an IP address
  after_validation :geocode, :if => :address_changed?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_attached_file :avatar, styles: { medium: '152x152#' }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  geocoded_by :address
  after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  
  def index
    @comments = @post.comments.order("created_at ASC")

    respond_to do |format|
      format.html { render layout: !request.xhr? }
    end
  end

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      flash[:alert] = "Check the comment form, something went wrong."
      render root_path
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])

    if @comment.user_id == current_user.id
      @comment.delete
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end
  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :owned_post, only: [:edit, :update, :destroy]
  def index
    @user = current_user
    if params[:search].present?
      @posts = Post.near(params[:search], 50, :order => 'distance', :units => :km)
    else
      @posts = Post.all
    end
  end

  def show
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = "Your post has been created!"
      redirect_to @post
    else
      flash[:alert] = "Your new post couldn't be created!  Please check the form."
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post updated."
      redirect_to posts_path
    else
      flash.now[:alert] = "Update failed.  Please check the form."
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:image, :about, :title, :property_type, :beds, :location, :accommodates, :bathrooms, :bedrooms, :room_type, :amenities, :price, :house_rules, :address, :latitude, :longitude)
  end

  def set_post
    @post = Post.find(params[:id])
  end
  def owned_post
    unless current_user == @post.user
      flash[:alert] = "That post doesn't belong to you!"
      redirect_to root_path
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :owned_profile, only: [:edit, :update]
  def show
  @user = current_user
  @posts = User.find_by(user_name: params[:user_name]).posts.order('created_at DESC')
  end
  def edit
  @user = User.find_by(user_name: params[:user_name])
  end
  def update
    @user = User.find_by(user_name: params[:user_name])
    if @user.update(profile_params)
      flash[:success] = 'Your profile has been updated.'
      redirect_to profile_path(@user.user_name)
    else
      @user.erros.full_messages
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end
  private

  def set_user
  @user = User.find_by(user_name: params[:user_name])
  end

  def owned_profile
    @user = User.find_by(user_name: params[:user_name])
    unless current_user == @user
      flash[:alert] = "That profile doesn't belong to you!"
      redirect_to root_path
    end
  end

  def profile_params
    params.require(:user).permit(:avatar, :full_name, :bio, :languages, :response_time, :address, :full_name)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_image_select(post)
  return image_tag post.image.url(:medium),
                   id: 'image-preview',
                   class: 'img-responsive' if post.image.exists?
  image_tag 'placeholder.jpg', id: 'image-preview', class: 'img-responsive'
  end
  def profile_avatar_select(user)
  return image_tag user.avatar.url(:medium),
                   id: 'image-preview',
                   class: 'img-responsive img-circle profile-image' if user.avatar.exists?
  image_tag 'default-avatar.jpg', id: 'image-preview',
                                  class: 'img-responsive img-circle profile-image'
  end  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/comments/_comment.html.haml
#comment
  .user-name
    = link_to comment.user.user_name, profile_path(comment.user.user_name)
  .comment-content
    = comment.content
  - if comment.user == current_user
    = link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" }, remote: true do
      %span(class="glyphicon glyphicon-remove delete-comment")

app/views/comments/create.js.erb
$('#comments_<%= @post.id %>').append("<%=j render 'comments/comment', post: @post, comment: @comment %>");
$('#comment_content_<%= @post.id %>').val('')

app/views/comments/destroy.js.erb
$('#comments_<%= @post.id %>').html("<%= j render @post.comments, post: @post, comment: @comment %>");

app/views/comments/index.html.haml
= render @comments, post: @post

app/views/comments/show.html.haml
.posts-wrapper.row
  -@posts.each do |post|
    .post
      .post-head
        .thumb-img
        .user-name
          =post.user.user_name
      .image.center-block
        =link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post)
      .post-bottom
        .caption
          .user-name
            = post.user.user_name
          = post.caption
        - if post.comments
          - post.comments.each do |comment|
            .comment
              .user-name
                = comment.user.user_name
              .comment-content
                = comment.content
              - if comment.user == current_user
                = link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" }
        .comment-form
          = form_for [post, post.comments.new] do |f|
            = f.text_field :content, placeholder: 'Add a comment...'

app/views/layouts/_navbar.html.haml
- if user_signed_in?
  %nav.navbar.navbar-default
    .container-fluid.navbar-container
      .navbar-header
        %button.navbar-toggle.collapsed{"data-target" => "#bs-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
          %span.sr-only Toggle Navigation
          %span.icon-bar
          %span.icon-bar
        .navbar-brand
          = link_to "FireBnb", root_path
      .collapse.navbar-collapse#bs-navbar-collapse-1
        %ul.nav.navbar-nav.navbar-right
          %li
            = link_to "New Listing", new_post_path
          %li.out
            %button.btn.btn-default.btn-lg{"aria-label" => "Right Align", :type => "button"}
              %span.glyphicon.glyphicon-off{"aria-hidden" => "true"}
            = link_to " ", destroy_user_session_path, class: 'log', method: :delete

app/views/layouts/application.html.haml
%html
  %head
    %title Instagram
    %link{:crossorigin => "anonymous", :href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css", :integrity => "sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u", :rel => "stylesheet"}/
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    = render 'layouts/navbar'
    .container
      -flash.each do |name, msg|
        = content_tag :div, msg, class: [:alert]
      = yield

app/views/posts/_form.html.haml
.posts-wrapper
  .post
    .post-body
      .image-wrap
        = form_image_select(@post)
        = simple_form_for @post, html: { multipart: true } do |f|
          .row
            .col-md-12.text-center
              = f.error_notification
          .container-fluid
            .form-group.text-center
              %h4 Upload an image:
              = f.input :image, label: false, input_html: { onChange: 'loadFile(event)' }
            .form-group.text-center
              = f.input :title, label: false, placeholder: 'Title of your listing'
            .form-group.text-center
              = f.input :address, label: false, placeholder: 'Address'
            .form-group.text-center
              = f.input :about, label: false, placeholder: 'About this listing'
            .form-group.text-center
              = f.input :accommodates, label: false, placeholder: 'Accommodates'
            .form-group.text-center
              = f.input :bathrooms, label: false, placeholder: 'Bathrooms'
            .form-group.text-center
              = f.input :bedrooms, label: false, placeholder: 'Bedrooms'
            .form-group.text-center
              = f.input :beds, label: false, placeholder: 'Beds'
            .form-group.text-center
              = f.input :property_type, label: false, placeholder: 'Property type'
            .form-group.text-center
              = f.input :room_type, label: false, placeholder: 'Room type'
            .form-group.text-center
              = f.input :amenities, label: false, placeholder: 'Amenities'
            .form-group.text-center
              = f.input :price, label: false, placeholder: 'Price'
            .form-group.text-center
              = f.input :house_rules, label: false, placeholder: 'House Rules'
            .form-group.text-center
              = f.button :submit, class: 'btn-success btn-block'

app/views/posts/_post.html.haml
.posts-wrapper.row
  .post
    .post-head
      .thumb-img
      .user-name
        = link_to post.user.user_name, profile_path(post.user.user_name)
      .time-ago
        = time_ago_in_words post.created_at
    .image.center-block
      = link_to (image_tag post.image.url, class:'img-responsive'), post_path(post)
    .post-bottom
      .caption
        .caption-content
          .user-name
            = link_to post.user.user_name, profile_path(post.user.user_name)
          = post.title
          = post.property_type
          = post.beds
          = post.address

app/views/posts/_posts.html.haml
-@posts.each do |post|
  = render 'post', post: post

app/views/posts/edit.html.haml
= render 'form'
.text-center.edit-links
  = link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" }
  |
  = link_to "cancel", posts_path

app/views/posts/index.html.erb
<div class="posts-wrapper row"></div>
<div class="row" id="searchfix">
  <%= form_tag posts_path, :method => :get do %>
    <p>
      <%= text_field_tag :search, params[:search], :id => "searchbar" %>
      <%= submit_tag "Search", :name => nil , :id => "searchbtn" %>
    </p>
  <% end %>
  <% @posts.each do |post| %>
    <div class="col-md-6 box">
      <div class="post">
        <div class="post-head">
          <div class="name">
            <%= link_to post.user.user_name, profile_path(post.user.user_name) %>
          </div>
        </div>
        <div class="image center-block">
          <%= link_to (image_tag post.image.url, class:'img-responsive'), post_path(post) %>
        </div>
        <p class="caption"></p>
        <h1>
          <%= post.title %>
        </h1>
        <br/>
        <p>
          <span class="glyphicon glyphicon-map-marker"></span>
          <%= post.address %>
        </p>
      </div>
    </div>
  <% end %>
</div>

  <% my_url = "http://maps.google.com/maps/api/staticmap?size=400x500&sensor=false&zoom=12" %>
  <% @posts.each do |post| %>
  <% my_url += "&markers=#{post.latitude}%2C#{post.longitude}" %>
  <% end %>
  <%= image_tag my_url , class:'indexmap' %>

app/views/posts/index.js.erb
$('#posts').append("<%= escape_javascript(render 'posts')%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); }  

app/views/posts/new.html.haml
= render 'form'
.text-center.edit-links
  = link_to "Cancel", posts_path
  %br/

app/views/posts/show.html.erb
<%= render 'post', post: @post %>
<div class="post-bottom">
  <div class="caption">
    <div class="caption-content">
      <%= @post.title %>
      <br/>
      <%= @post.about %>
      <br/>
      <%= @post.accommodates %>
      <br/>
      <%= @post.bathrooms %>
      <br/>
      <%= @post.bedrooms %>
      <br/>
      <%= @post.beds %>
      <br/>
      <%= @post.property_type %>
      <br/>
      <%= @post.room_type %>
      <br/>
      <%= @post.amenities %>
      <br/>
      <%= @post.price %>
      <%= @post.house_rules %>
    </div>
  </div>
</div>
<%= @post.address %>
<div class = "col-xs-12 col-sm-12 col-md-7 col-lg-7" id="showroommap">
<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@post.latitude}%2C#{@post.longitude}" %>
</div>
<% if @post.user.id == current_user.id %>
  <div class="text-center edit-links">
    <%= link_to "Cancel", posts_path %>
    |
    <%= link_to "Edit Post", edit_post_path(@post) %>
  </div>
<% else %>
  <div class="text-center edit-links">
    <%= link_to "Cancel", posts_path %>
  </div>
<% end %>

app/views/profiles/edit.html.haml
.posts-wrapper
  .post
    .post-body
      .image-wrap
        = simple_form_for @user, url: {action: "update"}, html: { multipart: true } do |f|
          .row
            .col-md-12
              .form-group.text-center
                %h4 Change your profile image:
                .img-circle.avatar-image
                  = profile_avatar_select(@user)
                = f.input :avatar, label: false,
                                   input_html: { onChange: 'loadFile(event)' }
          .row
            .col-md-1
            .col-md-10.text-center
              .form-group.text-center
                = f.input :full_name, label: false, placeholder: 'Full name'
                = f.input :languages, label: false, placeholder: 'Languages'
                = f.input :response_time, label: false, placeholder: 'Response Time'
                = f.input :address, label: false, placeholder: 'Where you live'
                = f.input :bio, label: false, placeholder: 'About yourself', input_html: { rows: 4 }
            .col-md-1
          .form-group.text-center
            = f.button :submit, 'Update Profile', class: 'btn btn-success'

app/views/profiles/show.html.haml
.posts-wrapper
  .row.profile-header
    .col-md-6
      .img-circle
        = profile_avatar_select(@user)
    .col-md-6
      %h3
        = @user.full_name
      %span
        - if @user == current_user
          = link_to 'Edit Profile', edit_profile_path(@user.user_name),
                                    class: 'btn edit-button'
      %p.profile-bio
        = @user.bio
        = @user.languages
        = @user.response_time
        = @user.address
      .user-statistics
        %p
          = pluralize @user.posts.count, 'post'

-@posts.each do |post|
  = render 'posts/post', post: post